application: django-profile
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /load
  script: userprofile/fixtures/loaddata.py
  login: admin

- url: /.*
  script: main.py

